name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment-config:
    uses: ./.github/workflows/deployment-config-reusable.yml

  frontend:
    uses: ./.github/workflows/frontend-reusable.yml

  lint:
    uses: ./.github/workflows/lint-reusable.yml
    with:
      go-version-file: backend/recap/go.mod

  test:
    needs: lint
    uses: ./.github/workflows/test-reusable.yml
    with:
      go-version-file: backend/recap/go.mod

  integration-test:
    needs: test
    uses: ./.github/workflows/test-integration-reusable.yml
    with:
      go-version-file: backend/recap/go.mod
