name: Lint reusable

on:
  workflow_call:
    inputs:
      go-version-file:
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Lint backend
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache: false

      - name: Generate code
        run: make generate

      - name: Verify golangci-lint configuration
        run: make lint-config

      - name: Run golangci-lint
        run: make lint
