name: Unit tests reusable

on:
  workflow_call:
    inputs:
      go-version-file:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache: false

      - name: Generate code
        run: make generate

      - name: Run go vet
        run: make vet

      - name: Check Go module files
        run: make tidy-check

      - name: Run unit tests with race detector
        run: make test-race
